export const TOKENS_SET = 'TOKENS_SET';

export const VALIDATOR_FETCH_IN_PROGRESS = 'VALIDATOR_FETCH_IN_PROGRESS';
export const VALIDATOR_FETCH_SUCCESS = 'VALIDATOR_FETCH_SUCCESS';
export const VALIDATOR_FETCH_ERROR = 'VALIDATOR_FETCH_ERROR';

export const DELEGATED_VALIDATORS_FETCH_IN_PROGRESS = 'DELEGATED_VALIDATORS_FETCH_IN_PROGRESS';
export const DELEGATED_VALIDATORS_FETCH_SUCCESS = 'DELEGATED_VALIDATORS_FETCH_SUCCESS';
export const DELEGATED_VALIDATORS_FETCH_ERROR = 'DELEGATED_VALIDATORS_FETCH_ERROR';

export const CLAIM_REWARDS_VALIDATOR_SET = 'CLAIM_REWARDS_VALIDATOR_SET';

export const VALIDATOR_IMAGE_FETCH_IN_PROGRESS = 'VALIDATOR_IMAGE_FETCH_IN_PROGRESS';
export const VALIDATOR_IMAGE_FETCH_SUCCESS = 'VALIDATOR_IMAGE_FETCH_SUCCESS';
export const VALIDATOR_IMAGE_FETCH_ERROR = 'VALIDATOR_IMAGE_FETCH_ERROR';
